// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC0uHzdWRgFMqqn56ouPaGSn0X-4GYDAA',
    appId: '1:454554613352:web:d46281f9f3a9ea0c8b2ddd',
    messagingSenderId: '454554613352',
    projectId: 'armtest1-114fa',
    authDomain: 'armtest1-114fa.firebaseapp.com',
    storageBucket: 'armtest1-114fa.appspot.com',
    measurementId: 'G-FPH7QFW6MX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwae7WKykvQbShaJEggVVCLyh9gI6gtqg',
    appId: '1:454554613352:android:ef72f94b7e64fb558b2ddd',
    messagingSenderId: '454554613352',
    projectId: 'armtest1-114fa',
    storageBucket: 'armtest1-114fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYSRdBNRN5FnlRos_Lae4_ZMkFr7DlaCU',
    appId: '1:454554613352:ios:43f9cdea3aeaf4598b2ddd',
    messagingSenderId: '454554613352',
    projectId: 'armtest1-114fa',
    storageBucket: 'armtest1-114fa.appspot.com',
    iosBundleId: 'com.example.armTest1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYSRdBNRN5FnlRos_Lae4_ZMkFr7DlaCU',
    appId: '1:454554613352:ios:f3d8e12522169db88b2ddd',
    messagingSenderId: '454554613352',
    projectId: 'armtest1-114fa',
    storageBucket: 'armtest1-114fa.appspot.com',
    iosBundleId: 'com.example.armTest1.RunnerTests',
  );
}
